baseURL = 'https://nsddd.top'
languageCode = 'en-us'
title = 'cubxxw is blog'
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]

# æ˜æš—è½¬æ¢
  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35
# å¯ç”¨æ—¶æ˜¾ç¤ºä¸ªäººèµ„æ–™å¡ç‰‡
  [params.profileMode]
  enabled = true
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "images/avatar.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"
# ä»…åœ¨ Profile Mode ç¦ç”¨æ—¶æ˜¾ç¤º
    [[params.profileMode.buttons]]
    name = "go"
    url = "go"
	
    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there ğŸ‘‹"
  Content = "Welcome to my blog"


  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/"


[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "example"
name = "example.org"
url = "https://example.org"
weight = 30
